name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *" # roda a cada 6 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Gerar stats
        run: |
          curl -L --fail -o stats.svg "https://github-readme-stats.vercel.app/api?username=pedrolima-07&show_icons=true&theme=transparent&title_color=1F6FEB&icon_color=1F6FEB&text_color=FFFFFF"
          curl -L --fail -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=pedrolima-07&layout=compact&theme=transparent&title_color=1F6FEB&text_color=FFFFFF"

      - name: Commitar arquivos
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add stats.svg langs.svg
          git commit -m "update stats" || echo "sem mudanças"
          git push
